[package]
name = "vak-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
globset = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
vak-agent = { workspace = true }
vak-config = { workspace = true }
vak-hooks = { workspace = true }
vak-llm = { workspace = true }
vak-mcp = { workspace = true }
vak-permission = { workspace = true }
vak-session = { workspace = true }
vak-tools = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
