export type Project = { id: string; root: string; display_name?: string | null };
export type Session = { id: string; project_id: string; created_at: string; status: string };
export type Run = { run_id: string; project_id: string; capability_epoch: number; status: string };
export type ConfigResponse = { revision: number; config: Record<string, unknown>; warnings: string[] };
export type Diagnostics = { status: string; details: Record<string, unknown> };
export type Event = Record<string, unknown>;
export type Task = { id: string; project_id?: string | null; spec: Record<string, unknown>; status: string; updated_at: string };
export type Memory = { id: string; project_id?: string | null; scope: string; kind: string; tag: string; text: string; created_at: string; updated_at: string; deleted_at?: string | null };
export type Inbox = { id: string; channel: string; external_id?: string | null; payload: Record<string, unknown>; created_at: string; acknowledged_at?: string | null };
