[package]
name = "vak-hooks"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
vak-permission = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
