[package]
name = "vakcoder"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vakcoder"
path = "src/main.rs"

[dependencies]
vak-agent = { workspace = true }
vak-config = { workspace = true }
vak-core = { workspace = true }
vak-llm = { workspace = true }
vak-session = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true
